# Artificial Neural Network

### Importing the libraries

In [37]:
import numpy as np
import pandas as pd


In [38]:
import tensorflow as tf

In [39]:
ann = tf.keras.models.Sequential()

In [40]:
tf.__version__

'2.17.0'

In [41]:
dataset = pd.read_csv('Churn_Modelling.csv')


In [42]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [43]:
X= dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [44]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [45]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
X[:,2]=lb.fit_transform(X[:,2])

In [46]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct =ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])], remainder='passthrough')
X= ct.fit_transform(X)

In [47]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [50]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=sc.fit_transform(X_train)

In [51]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [52]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7189 - loss: 0.6239
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.7974 - loss: 0.4586
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.7944 - loss: 0.4497
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.8016 - loss: 0.4354
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.8051 - loss: 0.4398
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.8213 - loss: 0.4193
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.8189 - loss: 0.4226
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.8245 - loss: 0.4100
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8237 - loss: 0.4087
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 996us/step - accuracy: 0.8273 - loss: 0.4091
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.8260 - loss: 0.4057
Epoch 12/100
250/250 ━━

In [54]:
y_pred = ann.predict(sc.transform(X_test))
y_pred =(y_pred>.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step


In [55]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [56]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[1488  107]
 [ 177  228]]
0.858
